---
- name: Configure the kernel to keep connections alive when enabling the firewall
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

# Install firewall : packages, certificates, configuration files
- name: Include OS specific vars
  include_vars: "{{ ansible_facts['os_family'] }}.yml"
  no_log: true

- name: Install task requirements
  include_tasks: "install-{{ ansible_facts['os_family'] }}.yml"

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: "Configure ufw ports and set state to {{ firewall_ufw_state }}"
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  loop: "{{ firewall_allowed_ports }}"

# You should install Docker before this rule.
- name: Configure ufw before.init to remove existing rules
  blockinfile:
    path: /etc/ufw/before.init
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: stop\)
    block: |
      iptables -F DOCKER-USER || true
      iptables -A DOCKER-USER -j RETURN || true
      iptables -X ufw-user-input || true

- name: Configure ufw before.init to drop ICMP timestamps
  blockinfile:
    path: /etc/ufw/before.init
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ICMP"
    insertafter: stop\)
    block: |
      iptables -A INPUT -p icmp --icmp-type timestamp-request -j DROP || true
      iptables -A OUTPUT -p icmp --icmp-type timestamp-reply -j DROP || true

- name: Chmod /etc/ufw/before.init
  file:
    path: /etc/ufw/before.init
    state: touch
    mode: "a+x"

- name: Configure ufw to work with DOCKER-USER chain name
  blockinfile:
    path: /etc/ufw/after.rules
    marker: "# {mark} ANSIBLE MANAGED BLOCK (docker-user)"
    block: |
      *filter
      :DOCKER-USER - [0:0]
      :ufw-user-input - [0:0]
      :ufw-after-logging-forward - [0:0]

      -A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A DOCKER-USER -m conntrack --ctstate INVALID -j DROP
      -A DOCKER-USER -i {{ ansible_default_ipv4.interface }} -j ufw-user-input
      -A DOCKER-USER -i {{ ansible_default_ipv4.interface }} -j ufw-after-logging-forward
      -A DOCKER-USER -i {{ ansible_default_ipv4.interface }} -j DROP

      COMMIT

- name: Set fact for ufw command
  set_fact:
    firewall_ufw_command: "{{ 'enable' if firewall_ufw_state == 'enabled' else 'disable' }}"

- name: Restart ufw to {{ firewall_ufw_state }}"
  command: "ufw {{ firewall_ufw_command }}"

- name: Log ufw status
  shell:
    cmd: "set -o pipefail && ufw status | grep Status"
    executable: /bin/bash


  register: ufw_status
  changed_when: false

- name: Debug ufw status
  debug:
    var: ufw_status.stdout
  when: ufw_status.stdout is defined

- name: Fail if ufw is not running
  fail:
    msg: "ufw is not running"
  when:
    - ufw_status.stdout is defined
    - firewall_ufw_state == 'enabled' and "active" not in ufw_status.stdout

- name: Fail if ufw is running
  fail:
    msg: "ufw is running"
  when:
    - ufw_status.stdout is defined
    - firewall_ufw_state == 'disabled' and "inactive" not in ufw_status.stdout
