---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: manager
    image: geerlingguy/docker-ubuntu2204-ansible
    # image: geerlingguy/docker-centos8-ansible
    hostname: manager
    groups:
      - fleet
    children:
      - managers
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/docker # needed for docker storage engine to be overlay2 instead of vfs
      # - /var/run/docker.sock:/var/run/docker.sock
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
    privileged: true
    networks:
      - name: "testfleet"
    network_mode: "bridge"
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
  - name: worker
    image: geerlingguy/docker-ubuntu2204-ansible
    # image: geerlingguy/docker-centos8-ansible
    hostname: worker
    groups:
      - fleet
    children:
      - workers
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/docker # needed for docker storage engine to be overlay2 instead of vfs
      # - /var/run/docker.sock:/var/run/docker.sock
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
    privileged: true
    networks:
      - name: "testfleet"
    network_mode: "bridge"
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
  sudo: False
  inventory:
    # host_vars:
    #   manager:
    #   worker:
    links:
      group_vars: ../../playbooks/group_vars/
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint molecule/default/prepare.yml
  ansible-lint molecule/default/converge.yml
  yamllint ./playbooks/ ./roles/ ./playbooks/group_vars/
