---
# Apply hardening to the cluster

# Playbook variables
# hardening__home_folders:
#   - /root
#   - /home/ubuntu
# hardening__os: true
# hardening__ssh: true
# hardening__firewall_state: enabled

- name: Apply firewall configuration on workers
  hosts: workers
  any_errors_fatal: true
  tags:
    - ufw
    - firewall
  roles:
    - role: firewall
      become: true
      vars:
        firewall_ufw_state: "{{ hardening__firewall_state }}"
        firewall_allowed_ports: "{{ hardening__firewall_allowed_ports }}"

- name: Secure kernel parameters on workers and managers
  hosts: workers, managers
  any_errors_fatal: true
  tags:
    - hardening
  roles:
    - role: config_kernel_params # Close icmp redirects and secure the kernel
      become: true

- name: Secure default umask on workers and managers
  hosts: workers, managers
  any_errors_fatal: true
  tags:
    - hardening
  roles:
    - role: config_default_umask
      become: true

- name: Secure home folders permissions on workers and managers
  hosts: workers, managers
  tags:
    - hardening
  tasks:
    - name: Adjust permission of home folders
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: '750'
      loop: "{{ hardening__home_folders }}"

- name: Remove unsecure packages from workers
  hosts: workers
  tags:
    - hardening
  tasks:
    - name: Purge unsecure packages
      become: true
      apt:
        name: {{ item }}
        state: absent
        purge: true
        autoremove: true
      when: ansible_facts['os_family'] == 'Debian'
      with_items:
        - telnet
        - samba

- name: Apply Fleet OS and SSH hardening
  hosts: workers
  tags:
    - hardening
  collections:
    - devsec.hardening
  roles:
    - role: devsec.hardening.os_hardening
      become: true
      when: hardening__os is defined and hardening__os
    - role: devsec.hardening.ssh_hardening
      become: true
      when: hardening__ssh is defined and hardening__ssh
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding required for docker.
      net.ipv4.ip_forward: 1
    ansible_role_name: "OS hardening"
    # Required for correct systemd pip package installed in fleet install playbook.
    ansible_default_interpreter: "/usr/bin/python3"
