name: "CI - On main branches"
on:
  push:
    branches:
      - main
      - 'releases/**'
    paths-ignore:
      - ".bumpversion.cfg"

jobs:
  Deploy:
    timeout-minutes: 30
    name: "Deploy Script"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install raise requirements
      run: python3 -m pip install -r build-requirements.txt

    - name: Raise App version
      id: raise
      run: |
        git config --global --add safe.directory $(pwd)
        git config --global user.name ${{ secrets.RAISE_BOT_COMMIT_USER }}
        git config --global user.email ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
        bump2version patch --no-tag
        version=$(cat version)
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Set branch output
      id: var_branch
      run: |
        echo "Branch name is: ${GITHUB_REF#refs/heads/}"
        echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

    - name: Raise App version
      uses: CasperWA/push-protected@v2.14.0
      with:
        token: ${{ secrets.RAISE_BOT_COMMIT_PASSWORD }}
        branch: ${{ steps.var_branch.outputs.branch }}
        unprotect_reviews: true

    - name: Commit of version
      id: commit_id
      run: |
        commit_hash=$(git log --format="%H" -n 1)
        echo "commit_id=$commit_hash" >> $GITHUB_OUTPUT

    - name: Create Github Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Release of ${{ steps.raise.outputs.version }}"
        body: "Please add release notes"
        tag_name: ${{ steps.raise.outputs.version }}
        target_commitish: ${{ steps.commit_id.outputs.commit_id }}
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        generate_release_notes: true
