name: "CI - On main/dev/release branches"
on:
  pull_request:
    branches:
      - dev
      - main
      - 'releases/**'
    paths-ignore:
      - 'debian/changelog'
jobs:
  Sanity:
    timeout-minutes: 90
    name: "Sanity checks"
    runs-on: [ self-hosted, Linux, docker, test ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install python 3.9 on host
      run: |
        sudo apt install -y python3.9 python3.9-venv

    - name: Install test dependencies
      run: |
        python3.9 -m venv molecule-venv
        source molecule-venv/bin/activate
        pip3 install -r requirements.txt
        ansible-galaxy collection install -r requirements.yml
        deactivate

    - name: Lint
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'
      run: |
        source molecule-venv/bin/activate
        ansible-lint install.yml update.yml
        deactivate

    - name: Molecule tests
      run: |
        source molecule-venv/bin/activate
        molecule converge -- --skip-tags ldap --extra-vars '{"fleet_extra_hosts": ["172.22.0.106 registry.hel.mov.ai traefik"]}'
        deactivate
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'

    - name: Molecule clean
      if: always()
      run: |
        source molecule-venv/bin/activate
        molecule destroy
        deactivate
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'

    - name: Docker cleanups
      if: always()
      shell: bash
      run: |
        docker system prune -f
        docker image prune -f --all
        rm -rf molecule-venv/
